# Generated by Django 3.1.4 on 2020-12-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectmodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'verbose_name_plural': 'Proyectos'},
        ),
    ]
