# Generated by Django 3.1.5 on 2021-05-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_auto_20210429_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Posts'},
        ),
    ]
